# Generated by Django 5.1.7 on 2025-05-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_jobrole_required_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Core', 'Core')], default='Technical', max_length=20),
        ),
    ]
