# Generated by Django 5.1.7 on 2025-05-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_extraction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatejobmatch',
            name='analyzed_at',
        ),
    ]
